+++
# Project title.
title = "Mansfield Trails"

# Date this page was created.
date = 2020-05-28T00:00:00

# Project summary to display on homepage.
summary = "ArcOnline map of trails for the Town of Mansfield"

# Tags: can be used for filtering projects.
# Example: `tags = ["machine-learning", "deep-learning"]`
tags = ["All"]

# Optional external URL for project (replaces project detail page).
external_link = ""

# Slides (optional).
#   Associate this project with Markdown slides.
#   Simply enter your slide deck's filename without extension.
#   E.g. `slides = "example-slides"` references 
#   `content/slides/example-slides.md`.
#   Otherwise, set `slides = ""`.
slides = "example-slides"

# Links (optional).
url_pdf = ""
url_slides = ""
url_video = ""
url_code = ""


# Featured image
# To use, add an image named `featured.jpg/png` to your project's folder. 
[image]
  # Caption (optional)
  caption = "Photo by rawpixel on Unsplash"
  
  # Focal point (optional)
  # Options: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight
  focal_point = "Smart"
+++

### I have been helping with Joshua's Trust and the Town of Mansfield to develop an application in ArcGIS Online for local trail information. Pulling together town, state, and land trust trail to one place and provide useful information for those who would like to recreate in the Mansfield, CT. This project is still in progress, but an example of the trail mapper can be found below. 

<style>.embed-container {position: relative; padding-bottom: 80%; height: 0; max-width: 100%;} .embed-container iframe, .embed-container object, .embed-container iframe{position: absolute; top: 0; left: 0; width: 100%; height: 100%;} small{position: absolute; z-index: 40; bottom: 0; margin-bottom: -15px;}</style><div class="embed-container"><iframe width="500" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" title="Mansfield_TrailMap_09092019" src="https://joshuastrust.maps.arcgis.com/apps/View/index.html?appid=624855de80744c0f916567ecc662a7f1"></iframe></div>

<br><br><br>

